version: "3.9"


services:
  backend:
    container_name: go_backend
    build:
     context: ./backend
     dockerfile: Dockerfile
    ports:
      - 5000:5000
  #  depends_on:
  #    postgres:
  #     condition: service_healthy

#volumes:
 # data_postgres: {}