version: "3.9"


services:
  postgres:
    container_name: postgresdb
    image: postgres:16
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    env_file:
     - .env
    healthcheck:
      test: pg_isready -d $POSTGRES_DB -U $POSTGRES_USER
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    container_name: go_backend
    build:
     context: ./backend
     dockerfile: Dockerfile
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_PORT: ${POSTGRES_PORT}
       POSTGRES_HOST: postgres
       PORT: 5000

    ports:
      - '5000:5000'
    depends_on:
      postgres:
       condition: service_healthy

volumes:
  data_postgres: {}